version: "3.3"

services:
  petsitter-web:
    image: ponelat/petsitter-web:latest
    environment:
      - 'DB_URL=mongodb://petsitter-db:27017'
    ports:
      - "443:8080"
    networks:
      - designapis

  mongo-express:
    image: mongo-express:latest
    environment:
      - 'ME_CONFIG_MONGODB_SERVER=petsitter-db'

  petsitter-db:
    image: mongo:4.2.3
    networks:
      - designapis
    volumes:
      - type: volume
        source: petsitter-db
        target: /data/db

  # Let's Encrypt Stuff...
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=designapis.com
    networks:
      - designapis

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - designapis

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - designapis

networks:
  designapis:
volumes:
  petsitter-db:
  conf:
  vhost:
  html:
  dhparam:
  certs:
