version: "3.3"

services:
  petsitter:
    image: designapis/petsitter:latest
    environment:
      - 'DB_URL=mongodb://petsitter-db/petsitter-db'
    ports:
      - "8080:8080"
    networks:
      - designapis

  mongo-express:
    image: mongo-express:latest
    networks:
      - designapis
    ports:
      - "8081:8081"
    environment:
      - 'ME_CONFIG_MONGODB_SERVER=petsitter-db'

  petsitter-db:
    image: mongo:4.2.3
    networks:
      - designapis
    volumes:
      - type: volume
        source: petsitter-db
        target: /data/db

networks:
  designapis:
volumes:
  petsitter-db:
